version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/procase/
permissions:
  - object: scripts/
    pattern: "start_server.sh"
    mode: 777
    type:
      - file

hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
